apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-service
  template:
    metadata:
      labels:
        app: registry-service
    spec:
      containers:
      - name: registry-service
        image: maheribrahim/devops2023:registry-service-latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: registry-service
spec:
  selector:
    app: registry-service
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
